"""add user-login relationship

Revision ID: 0dd708c52756
Revises: 7c40e57b748a
Create Date: 2019-11-02 02:31:19.499652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dd708c52756'
down_revision = '7c40e57b748a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_history',
    sa.Column('in_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.admin_id'], name=op.f('fk_login_history_admin_id_admin')),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name=op.f('fk_login_history_user_id_user')),
    sa.PrimaryKeyConstraint('in_id', name=op.f('pk_login_history'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('login_history')
    # ### end Alembic commands ###
