"""models: integrate promotion

Revision ID: 15243a10e197
Revises: 9b10bd5ee80a
Create Date: 2019-11-10 07:25:18.169885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15243a10e197'
down_revision = '9b10bd5ee80a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promotion',
    sa.Column('promotion_id', sa.Integer(), nullable=False),
    sa.Column('promo_percentage', sa.Integer(), nullable=True),
    sa.Column('dt_start', sa.DateTime(), nullable=True),
    sa.Column('dt_end', sa.DateTime(), nullable=True),
    sa.Column('promo_code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('promotion_id', name=op.f('pk_promotion'))
    )
    op.create_table('event_promotion',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('promotion_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.event_id'], name=op.f('fk_event_promotion_event_id_event')),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotion.promotion_id'], name=op.f('fk_event_promotion_promotion_id_promotion')),
    sa.PrimaryKeyConstraint('event_id', 'promotion_id', name=op.f('pk_event_promotion'))
    )
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('promotion_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_payment_promotion_id_promotion'), 'promotion', ['promotion_id'], ['promotion_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_payment_promotion_id_promotion'), type_='foreignkey')
        batch_op.drop_column('promotion_id')

    op.drop_table('event_promotion')
    op.drop_table('promotion')
    # ### end Alembic commands ###
