"""add LogoutHistory

Revision ID: 19917246b7ea
Revises: d90425d0c788
Create Date: 2019-11-02 05:29:39.278539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19917246b7ea'
down_revision = 'd90425d0c788'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logout_history',
    sa.Column('out_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.admin_id'], name=op.f('fk_logout_history_admin_id_admin')),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name=op.f('fk_logout_history_user_id_user')),
    sa.PrimaryKeyConstraint('out_id', name=op.f('pk_logout_history'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logout_history')
    # ### end Alembic commands ###
