"""add Booking

Revision ID: 263b3f68a232
Revises: a3413fce549e
Create Date: 2019-11-18 05:00:06.961960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '263b3f68a232'
down_revision = 'a3413fce549e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking',
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_slot_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_slot_id'], ['event_slot.slot_id'], name=op.f('fk_booking_event_slot_id_event_slot')),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name=op.f('fk_booking_user_id_user')),
    sa.PrimaryKeyConstraint('booking_id', name=op.f('pk_booking'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking')
    # ### end Alembic commands ###
