"""add usergroup and user models

Revision ID: 40bedff8501b
Revises: 
Create Date: 2019-11-17 07:13:35.971798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40bedff8501b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usergroup',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('group_id', name=op.f('pk_usergroup'))
    )
    with op.batch_alter_table('usergroup', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usergroup_group_name'), ['group_name'], unique=True)

    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['usergroup.group_id'], name=op.f('fk_user_group_id_usergroup')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user'))
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('usergroup', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usergroup_group_name'))

    op.drop_table('usergroup')
    # ### end Alembic commands ###
