"""update staff table

Revision ID: 511200d4cbdf
Revises: b1cd2edd3d9c
Create Date: 2019-10-22 22:42:22.145881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '511200d4cbdf'
down_revision = 'b1cd2edd3d9c'
branch_labels = None
depends_on = None


def upgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	with op.batch_alter_table('staff') as batch_op:
		batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=True))
		batch_op.drop_column('password')
    # ### end Alembic commands ###


def downgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	with op.batch_alter_table('staff') as batch_op:
		batch_op.add_column(sa.Column('password', sa.String(length=255), nullable=True))
		batch_op.drop_column('password_hash')
	# ### end Alembic commands ###
