"""Promotion: change attributes to non-nullable

Revision ID: 56a248485472
Revises: 69ad845f565d
Create Date: 2019-11-11 17:43:31.794068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56a248485472'
down_revision = '69ad845f565d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('promotion', schema=None) as batch_op:
        batch_op.alter_column('dt_end',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('dt_start',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('promo_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('promo_percentage',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('promotion', schema=None) as batch_op:
        batch_op.alter_column('promo_percentage',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('promo_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('dt_start',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('dt_end',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
