"""EventSlot: add is_active column

Revision ID: 7c40e57b748a
Revises: 6482766f5c90
Create Date: 2019-11-01 12:07:42.625812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c40e57b748a'
down_revision = '6482766f5c90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_slot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_slot', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
