"""add Refund

Revision ID: 811337ee3fba
Revises: f4696a14acf4
Create Date: 2019-11-18 08:25:07.676345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '811337ee3fba'
down_revision = 'f4696a14acf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refund',
    sa.Column('refund_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.payment_id'], name=op.f('fk_refund_payment_id_payment')),
    sa.PrimaryKeyConstraint('refund_id', name=op.f('pk_refund'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refund')
    # ### end Alembic commands ###
