"""models: add Refund

Revision ID: 8988f4b2d931
Revises: fe7c24788437
Create Date: 2019-11-08 21:25:19.182531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8988f4b2d931'
down_revision = 'fe7c24788437'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refund',
    sa.Column('refund_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.payment_id'], name=op.f('fk_refund_payment_id_payment')),
    sa.PrimaryKeyConstraint('refund_id', name=op.f('pk_refund'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refund')
    # ### end Alembic commands ###
