"""alter Event attributes

Revision ID: 94e88aafa1a4
Revises: b07038828876
Create Date: 2019-10-23 12:32:28.348260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94e88aafa1a4'
down_revision = 'b07038828876'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('event_type', sa.String(), nullable=True))
        batch_op.drop_column('type')
        batch_op.drop_column('date_start')
        batch_op.drop_column('date_end')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_end', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('date_start', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('type', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('event_type')
        batch_op.drop_column('duration')

    # ### end Alembic commands ###
