"""empty message

Revision ID: 979f18faedbd
Revises: 61c83840af10
Create Date: 2019-10-21 21:19:13.580706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '979f18faedbd'
down_revision = '61c83840af10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('date_end', sa.DateTime(), nullable=True))
    op.add_column('event', sa.Column('date_start', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'date_start')
    op.drop_column('event', 'date_end')
    # ### end Alembic commands ###
