"""staff table added indexing

Revision ID: 9be65d91fdf2
Revises: e70ebe7c74d2
Create Date: 2019-10-23 12:03:55.261683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9be65d91fdf2'
down_revision = 'e70ebe7c74d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_staff_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_username'))
        batch_op.drop_index(batch_op.f('ix_staff_email'))

    # ### end Alembic commands ###
