"""LogoutHistory: in_id change to out_id

Revision ID: 9ea2a10653cf
Revises: e975932af7f9
Create Date: 2019-11-02 04:42:26.961300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ea2a10653cf'
down_revision = 'e975932af7f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logout_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('out_id', sa.Integer(), nullable=False))
        batch_op.drop_column('in_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logout_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('in_id', sa.INTEGER(), nullable=False))
        batch_op.drop_column('out_id')

    # ### end Alembic commands ###
