"""booking: change booking_no to booking_id

Revision ID: aee90fd6536d
Revises: da87bad07e28
Create Date: 2019-11-07 02:40:12.881850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aee90fd6536d'
down_revision = 'da87bad07e28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.alter_column('booking_no', new_column_name='booking_id')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint('fk_payment_booking_id_booking', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_payment_booking_id_booking'), 'booking', ['booking_id'], ['booking_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_payment_booking_id_booking'), type_='foreignkey')
        batch_op.create_foreign_key('fk_payment_booking_id_booking', 'booking', ['booking_id'], ['booking_no'])

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.alter_column('booking_id', new_column_name='booking_no')

    # ### end Alembic commands ###
