"""temporarily drop EventSlot and Booking

Revision ID: b07038828876
Revises: 9be65d91fdf2
Create Date: 2019-10-23 12:27:00.656559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b07038828876'
down_revision = '9be65d91fdf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_slot')
    op.drop_table('booking')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking',
    sa.Column('booking_no', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('event_id', sa.INTEGER(), nullable=True),
    sa.Column('event_date', sa.DATETIME(), nullable=True),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['event_date'], ['event_slot.event_date'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.event_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('booking_no'),
    sa.UniqueConstraint('event_date'),
    sa.UniqueConstraint('event_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('event_slot',
    sa.Column('event_id', sa.INTEGER(), nullable=False),
    sa.Column('event_date', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.event_id'], ),
    sa.PrimaryKeyConstraint('event_id', 'event_date')
    )
    # ### end Alembic commands ###
