"""add events models

Revision ID: b2b735b54bb4
Revises: be63307f41d7
Create Date: 2019-10-30 03:35:49.172504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2b735b54bb4'
down_revision = 'be63307f41d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_type',
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('type_id', name=op.f('pk_event_type'))
    )
    with op.batch_alter_table('event_type', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_type_name'), ['name'], unique=True)

    op.create_table('venue',
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('venue_id', name=op.f('pk_venue'))
    )
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_venue_name'), ['name'], unique=True)

    op.create_table('event',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('img_root', sa.String(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['event_type.type_id'], name=op.f('fk_event_type_id_event_type')),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.venue_id'], name=op.f('fk_event_venue_id_venue')),
    sa.PrimaryKeyConstraint('event_id', name=op.f('pk_event'))
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_title'), ['title'], unique=False)

    op.create_table('event_slot',
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('event_date', sa.DateTime(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.event_id'], name=op.f('fk_event_slot_event_id_event')),
    sa.PrimaryKeyConstraint('slot_id', name=op.f('pk_event_slot'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_slot')
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_title'))

    op.drop_table('event')
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_venue_name'))

    op.drop_table('venue')
    with op.batch_alter_table('event_type', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_type_name'))

    op.drop_table('event_type')
    # ### end Alembic commands ###
