"""add EventPromotion

Revision ID: b59da7c9af32
Revises: 811337ee3fba
Create Date: 2019-11-18 08:59:21.313218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b59da7c9af32'
down_revision = '811337ee3fba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_promotion',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('promotion_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.event_id'], name=op.f('fk_event_promotion_event_id_event')),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotion.promotion_id'], name=op.f('fk_event_promotion_promotion_id_promotion')),
    sa.PrimaryKeyConstraint('event_id', 'promotion_id', name=op.f('pk_event_promotion'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_promotion')
    # ### end Alembic commands ###
