"""add booking model

Revision ID: bdd8cc15101f
Revises: aac55322d2c5
Create Date: 2019-10-30 13:59:38.711142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdd8cc15101f'
down_revision = 'aac55322d2c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking',
    sa.Column('booking_no', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_slot_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_slot_id'], ['event_slot.slot_id'], name=op.f('fk_booking_event_slot_id_event_slot')),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name=op.f('fk_booking_user_id_user')),
    sa.PrimaryKeyConstraint('booking_no', name=op.f('pk_booking'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking')
    # ### end Alembic commands ###
