"""Promotion: column name change

Revision ID: c6caefa7cfdb
Revises: 6925e1d05e8d
Create Date: 2019-11-12 20:46:25.055258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6caefa7cfdb'
down_revision = '6925e1d05e8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('promotion', schema=None) as batch_op:
        batch_op.alter_column('dt_start', new_column_name='date_start')
        batch_op.alter_column('dt_end', new_column_name='date_end')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('promotion', schema=None) as batch_op:
        batch_op.alter_column('date_start', new_column_name='dt_start')
        batch_op.alter_column('date_end', new_column_name='dt_end')

    # ### end Alembic commands ###
