"""models: add login and logout history

Revision ID: d735205619de
Revises: 40bedff8501b
Create Date: 2019-11-17 19:53:35.874328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd735205619de'
down_revision = '40bedff8501b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_history',
    sa.Column('in_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name=op.f('fk_login_history_user_id_user')),
    sa.PrimaryKeyConstraint('in_id', name=op.f('pk_login_history'))
    )
    op.create_table('logout_history',
    sa.Column('out_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name=op.f('fk_logout_history_user_id_user')),
    sa.PrimaryKeyConstraint('out_id', name=op.f('pk_logout_history'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logout_history')
    op.drop_table('login_history')
    # ### end Alembic commands ###
