"""empty message

Revision ID: d90425d0c788
Revises: 9ea2a10653cf
Create Date: 2019-11-02 05:24:37.784455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd90425d0c788'
down_revision = '9ea2a10653cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logout_history')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logout_history',
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('admin_id', sa.INTEGER(), nullable=True),
    sa.Column('out_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.admin_id'], name='fk_logout_history_admin_id_admin'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name='fk_logout_history_user_id_user')
    )
    # ### end Alembic commands ###
