"""empty message

Revision ID: e70ebe7c74d2
Revises: 511200d4cbdf
Create Date: 2019-10-23 11:36:42.988679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e70ebe7c74d2'
down_revision = '511200d4cbdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
	with op.batch_alter_table('staff') as batch:
		batch.alter_column('email', existing_type=sa.String(length=255), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
	with op.batch_alter_table('staff') as batch:
		batch.alter_column('email', existing_type=sa.String(length=255), nullable=True)
    # ### end Alembic commands ###
