"""add LogoutHistory

Revision ID: e975932af7f9
Revises: 0dd708c52756
Create Date: 2019-11-02 04:39:01.714450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e975932af7f9'
down_revision = '0dd708c52756'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logout_history',
    sa.Column('in_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.admin_id'], name=op.f('fk_logout_history_admin_id_admin')),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name=op.f('fk_logout_history_user_id_user')),
    sa.PrimaryKeyConstraint('in_id', name=op.f('pk_logout_history'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logout_history')
    # ### end Alembic commands ###
