"""added EventSlots

Revision ID: efca5f2588c7
Revises: ac776c6f1ae7
Create Date: 2019-10-23 16:04:33.006331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efca5f2588c7'
down_revision = 'ac776c6f1ae7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_slot',
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('event_date', sa.DateTime(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.event_id'], name=op.f('fk_event_slot_event_id_event')),
    sa.PrimaryKeyConstraint('slot_id', name=op.f('pk_event_slot'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_slot')
    # ### end Alembic commands ###
